name: mlops_framework
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  
  # Core dependencies
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.6.0
  - seaborn>=0.11.0
  - pyyaml>=6.0
  - requests>=2.28.0
  - urllib3>=1.26.0
  
  # Development and testing
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  
  # Pip dependencies (not available in conda-forge)
  - pip:
    - snowflake-connector-python[pandas]>=3.0.0
    - snowflake-ml-python>=1.9.0
    - xgboost>=1.7.0
    - joblib>=1.3.0
    - shap>=0.41.0
    - python-dotenv>=1.0.0 