apiVersion: v1
kind: Service
metadata:
  name: job-feature-engineering
  labels:
    pipeline: customer-churn
    node: feature-engineering
spec:
  containers:
    - name: feature-engineering-container
      image: <SNOWFLAKE_REGISTRY_URL>/mlops_framework:latest
      args:
        - "--node"
        - "engineer_features"
      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "6Gi"
          cpu: "4"
      env:
        - name: SNOWFLAKE_ACCOUNT
          value: "<SNOWFLAKE_ACCOUNT>"
        - name: SNOWFLAKE_USER
          value: "<SNOWFLAKE_USER>"
        - name: SNOWFLAKE_DATABASE
          value: "<SNOWFLAKE_DATABASE>"
        - name: SNOWFLAKE_SCHEMA
          value: "<SNOWFLAKE_SCHEMA>"
        - name: LOG_LEVEL
          value: "INFO"
  restartPolicy: Never
  computePool: MLOPS_COMPUTE_POOL 