apiVersion: v1
kind: Service
metadata:
  name: job-train-test-split
  labels:
    pipeline: customer-churn
    node: train-test-split
spec:
  containers:
    - name: train-test-split-container
      image: <SNOWFLAKE_REGISTRY_URL>/mlops_framework:latest
      args:
        - "--node"
        - "create_train_test_split"
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      env:
        - name: SNOWFLAKE_ACCOUNT
          value: "<SNOWFLAKE_ACCOUNT>"
        - name: SNOWFLAKE_USER
          value: "<SNOWFLAKE_USER>"
        - name: SNOWFLAKE_DATABASE
          value: "<SNOWFLAKE_DATABASE>"
        - name: SNOWFLAKE_SCHEMA
          value: "<SNOWFLAKE_SCHEMA>"
        - name: LOG_LEVEL
          value: "INFO"
  restartPolicy: Never
  computePool: MLOPS_COMPUTE_POOL 